use_frameworks!

platform :ios, '8.0'

target 'HYHSuspensionList_Example' do
  
  pod 'HYHSuspensionList', :path => '../'

  target 'HYHSuspensionList_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
